
[build]
  command = "npm run build"
  publish = "dist"

# redirect to english or spanish landing pages.

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

# redirect the 404 pages to your specific variant.


[[redirects]]
  from = "/es/*"
  to = "/es/404"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404